<?php


if (false) {
    define("_header_eposta_title", "E-posta G\u00f6nderin");
    define("_header_telefon_title", "Hemen Aray\u0131n");
    define("_header_whatsapp_title", "Whatsapp H\u0131zl\u0131 \u0130leti\u015fim");
    define("_header_facebook_title", "Facebook'ta bizi takip edin");
    define("_header_instagram_title", "Instagram'da bizi takip edin");
    define("_header_twitter_title", "Twitter'da bizi takip edin");
    define("_header_linkedin_title", "Linkedin'de bizi takip edin");
    define("_header_youtube_title", "Youtube'da bizi takip edin");
    define("_header_arama_title", "Arama Yap\u0131n");
    define("_header_ara_buton", "Ara");
    define("_header_uyegiris_title", "\u00dcye Giri\u015f");
    define("_header_favori_title", "Favorilerim");
    define("_header_sepetim_yazi", "Sepetim");
    define("_body_whatsapp_title", "Whatsapp H\u0131zl\u0131 \u0130leti\u015fim");
    define("_body_cerez_on_yazi", "\u0130nternet sitemizde \u00e7erezler vas\u0131tas\u0131yla ki\u015fisel verileriniz i\u015flenmektedir. Ki\u015fiselle\u015ftir butonu ile eri\u015febilece\u011finiz \u00c7erez Y\u00f6netim Paneli \u00fczerinden her zaman tercihlerinizi belirleyebilirsiniz. Daha detayl\u0131 bilgi i\u00e7in \u00c7erez ve Di\u011fer Tan\u0131mlama Teknolojilerine Y\u00f6nelik Ayd\u0131nlatma Metni'ni inceleyiniz. <a href=\"[cookiePolicyLink]\" target=\"_blank\">\u00c7erez ve Di\u011fer Tan\u0131mlama Teknolojilerine Y\u00f6nelik Ayd\u0131nlatma Metni<\/a>");
    define("_body_cerez_ret", "\u00c7erezleri Red Et");
    define("_body_cerez_onay", "\u00c7erezleri Kabul Et");
    define("_sepet_toplam_urun_modeli", "Toplam \u00dcr\u00fcn Modeli");
    define("_sepet_toplam_urun_adedi", "Toplam \u00fcr\u00fcn Adet");
    define("_sepet_sepet_toplam_tutar_yazi", "Toplam Tutar");
    define("_sepet_indirim_toplam_tutar_yazi", "\u0130ndirim Toplam Tutar");
    define("_sepet_indirimli_toplam_tutar_yazi", "\u0130ndirimli Toplam Tutar");
    define("_sepet_indirim_tutar_yazi", "\u0130ndirim Tutar\u0131");
    define("_sepet_sepete_git_yazi", "Sepete Git");
    define("_sepet_urun_stok_kod_yazi", "Stok Kodu");
    define("_sepet_urun_sil_yazi", "Sil");
    define("_sepet_odeme_yap_yazi", "Hemen \u00d6de");
    define("_sepet_sepetim_urun_yok_yazi", "Sepetinizde hi\u00e7 \u00fcr\u00fcn bulunmuyor");
    define("_urun_kutu_etiket_indirim_yazi", "\u0130ndirimde");
    define("_urun_kutu_etiket_yeni_yazi", "Yeni");
    define("_urun_kutu_etiket_ayni_gun_kargo", "Ayn\u0131 G\u00fcn Kargo");
    define("_urun_kutu_etiket_ucretsiz_kargo_yazi", "\u00dccretsiz Kargo");
    define("_urun_kutu_fiyat_sor_yazi", "Fiyat Sorunuz");
    define("_urun_detay_urun_fiyat_sor", "Fiyat Sorunuz");
    define("_urun_detay_urun_kategori_yazi", "Kategori");
    define("_urun_detay_urun_marka_yazi", "Marka");
    define("_urun_detay_urun_model_yazi", "Model");
    define("_urun_detay_urun_stok_kod_yazi", "Stok Kod");
    define("_urun_detay_urun_miktar_yazi", "Miktar");
    define("_urun_detay_sepete_ekle_buton", "Sepete Ekle");
    define("_urun_detay_hemen_al_yazi", "Hemen Al");
    define("_urun_detay_paylas_begen_yazi", "Be\u011fen \/ Payla\u015f");
    define("_urun_detay_fav_ekle_yazi", "Favorilere Ekle");
    define("_urun_detay_kargo_bilgi_yazi", "Kargo Bilgileri");
    define("_urun_detay_urun_aciklama_yazi", "A\u00e7\u0131klama");
    define("_urun_detay_urun_secenekleri", "\u00dcr\u00fcn Se\u00e7enekleri");
    define("_urun_detay_iliskili_urunler_yazi", "\u0130li\u015fkili \u00fcr\u00fcnler");
    define("_kategori_filtrele_yazi", "Filtrele");
    define("_kategori_filtre_temizle_yazi", "Filtreleri Temizle");
    define("_kategori_devamini_oku_yazi", "Devam\u0131n\u0131 Oku");
    define("_arama_sayfasi_filtrele_yazi", "Filtrele");
    define("_arama_sayfasi_filtre_temizle_yazi", "Filtreleri Temizle");
    define("_arama_sayfasi_sonuc_yazi", "Arama Sonucu");
    define("_arama_sayfasi_sonuc_adet_yazi", "Adet");
    define("_arama_sayfasi_sonuc_yok_yazi", "Hi\u00e7 \u00fcr\u00fcn bulunamad\u0131 :(");
    define("_uye_sayfasi_adreslerim_yazi", "Adreslerim");
    define("_uye_sayfasi_guncelle_yazi", "G\u00fcncelle");
    define("_uye_sayfasi_sil_yazi", "Sil");
    define("_uye_sayfasi_yeni_adres_yazi", "Yeni Adres");
    define("_uye_sayfasi_form_adres_baslik_yazi", "Adres Ba\u015fl\u0131k");
    define("_uye_sayfasi_form_tc_yazi", "TC No");
    define("_uye_sayfasi_form_adres_ad_yazi", "Ad");
    define("_uye_sayfasi_form_adres_soyad_yazi", "Soyad");
    define("_uye_sayfasi_form_adres_ulke", "\u00dclke");
    define("_uye_sayfasi_form_adres_sehir", "\u015eehir");
    define("_uye_sayfasi_form_adres_ilce", "\u0130l\u00e7e");
    define("_uye_sayfasi_form_adres_semt", "Semt");
    define("_uye_sayfasi_form_adres_mahalle", "Mahalle");
    define("_uye_sayfasi_form_adres_sokak", "Cadde \/ Sokak");
    define("_uye_sayfasi_form_adres_posta_kod", "Posta Kodu");
    define("_uye_sayfasi_form_adres_cep", "Cep Telefonu");
    define("_uye_sayfasi_form_adres_ekle_buton", "Kaydet");
    define("_odeme_sayfasi_hemenal_yazi", "Hemen Al");
    define("_odeme_sayfasi_yeni_adres_ekle_yazi", "Yeni Adres Ekle");
    define("_odeme_sayfasi_fatura_unvan_yazi", "(Kurumsal) Fatura \u00dcnvan \/ (Ki\u015fisel) \u0130sim Soyisim");
    define("_odeme_sayfasi_vergi_dairesi_yazi", "(Kurumsal) Vergi Dairesi \/ (Ki\u015fisel) \u0130l\u00e7eniz");
    define("_odeme_sayfasi_vergi_no_yazi", "(Kurumsal) Vergi No \/ (Ki\u015fisel) TC No");
    define("_odeme_sayfasi_kargo_adresi_olarak_kullan_yazi", "Kargo Adresi Olarak Kullan");
    define("_odeme_sayfasi_fatura_adresi_olarak_kullan_yazi", "Fatura Adresi Olarak Kullan");
    define("_odeme_sayfasi_devam_etmek_icin_giris_yapin_yazi", "\u00d6deme i\u015flemine devam edebilmek i\u00e7in giri\u015f yap\u0131n \/ Adres ekleyin");
    define("_odeme_sayfasi_urun_stok_kod_yazi", "Stok Kodu");
    define("_odeme_sayfasi_sepet_toplam_urun_modeli", "Toplam \u00fcr\u00fcn Modeli");
    define("_odeme_sayfasi_sepet_toplam_urun_adedi", "Toplam \u00fcr\u00fcn Adeti");
    define("_odeme_sayfasi_sepet_toplam_tutar_yazi", "Toplam Tutar");
    define("_odeme_sayfasi_sepet_indirim_toplam_tutar_yazi", "Toplam \u0130ndirim Tutar\u0131");
    define("_odeme_sayfasi_sepet_indirimli_toplam_tutar", "Toplam \u0130ndirimli Tutar");
    define("_odeme_sayfasi_musteri_notu_yazi", "Notunuz");
    define("_odeme_sayfasi_sozlesme_sartlari_kabul_yazi", "S\u00f6zle\u015fme \u015fartlar\u0131n\u0131 kabul ediyorum.");
    define("_odeme_sayfasi_odeme_yap_yazi", "\u00d6deme Yap");
    define("_odeme_sayfasi_sepetim_urun_yok_yazi", "Sepetinizde hi\u00e7 \u00fcr\u00fcn bulunmuyor.");
    define("_odeme_sayfasi_form_yeni_adres_ekle_yazi", "Yeni Adres Ekle");
    define("_odeme_sayfasi_form_tum_alan_zorunlu_yazi", "T\u00fcm alanlar zorunludur");
    define("_odeme_sayfasi_form_adres_cep_telefon_yazi", "Cep Telefonu");
    define("_odeme_sayfasi_form_adres_eposta_yazi", "E-posta");
    define("_odeme_sayfasi_form_adres_baslik_yazi", "Adres Ba\u015fl\u0131k");
    define("_odeme_sayfasi_form_adres_tc_yazi", "TC No");
    define("_odeme_sayfasi_form_adres_isim_yazi", "\u0130sim");
    define("_odeme_sayfasi_form_adres_soyisim_yazi", "Soyisim");
    define("_odeme_sayfasi_form_adres_ulke", "\u00dclke");
    define("_odeme_sayfasi_form_adres_sehir", "\u015eehir");
    define("_odeme_sayfasi_form_adres_ilce", "\u0130l\u00e7e");
    define("_odeme_sayfasi_form_adres_semt", "Semt");
    define("_odeme_sayfasi_form_adres_mahalle", "Mahalle");
    define("_odeme_sayfasi_form_adres_posta_kod", "Posta Kod");
    define("_odeme_sayfasi_form_adres_sokak", "Cadde \/ Sokak");
    define("_odeme_sayfasi_form_fatura_bilgileri_yazi", "Fatura Bilgileriniz");
    define("_odeme_sayfasi_form_fatura_unvan_yazi", "(Kurumsal) Fatura \u00dcnvan \/ (Ki\u015fisel) \u0130sim Soyisim");
    define("_odeme_sayfasi_form_fatura_vergi_dairesi_yazi", "(Kurumsal) Vergi Dairesi \/ (Ki\u015fisel) \u0130l\u00e7eniz");
    define("_odeme_sayfasi_form_fatura_vergi_no_yazi", "(Kurumsal) Vergi No \/ (Ki\u015fisel) TC No");
    define("_odeme_sayfasi_form_buton_yazi", "Kaydet");
    define("_footer_eposta_title", "E-Posta G\u00f6nderin");
    define("_footer_telefon_title", "Hemen Ara");
    define("_footer_whatsapp_title", "Whatsapp H\u0131zl\u0131 \u0130leti\u015fim");
    define("_footer_copyright_yazi", "Her Hakk\u0131 sakl\u0131d\u0131r");
    define("_uyelik_bilgilerim_yazi", "Bilgilerim");
    define("_sol_kapat_yazi", "Kapat");
    define("_sol_uyelik_cikis_yazi", "\u00c7\u0131k\u0131\u015f");
    define("_sol_uyelik_bilgilerim_yazi", "\u00dcyelik Bilgilerim");
    define("_sol_uyelik_sepetim_yazi", "Sepetim");
    define("_sol_uyelik_siparislerim_yazi", "Sipari\u015flerim");
    define("_sol_uyelik_adreslerim_yazi", "Adreslerim");
    define("_sol_uyelik_mesajlarim_yazi", "Mesajlar\u0131m");
    define("_sol_uyelik_favorilerim_yazi", "Favorilerim");
    define("_sol_uyelik_iptal_iade_degisim_yazi", "\u0130ptal \u0130ade De\u011fi\u015fim");
    define("_sol_ziyaretci_yazi", "Ziyaret\u00e7i Bilgileri");
    define("_giris_form_giris_yazi", "\u00dcye Giri\u015fi");
    define("_form_adres_ulke", "\u00dclke");
    define("_form_adres_sehir", "\u015eehir");
    define("_form_adres_ilce", "\u0130l\u00e7e");
    define("_form_adres_semt", "Semt");
    define("_form_adres_mahalle", "Mahalle");
    define("_form_adres_posta_kod", "Posta Kodu");
    define("_form_adres_sokak", "Cadde \/ Sokak");
    define("_form_adres_baslik_yazi", "Adres Ba\u015fl\u0131\u011f\u0131");
    define("_form_adres_tc_yazi", "TC Kimlik No");
    define("_form_adres_ad_yazi", "Ad");
    define("_form_adres_soyad_yazi", "Soyad");
    define("_form_adres_cep_yazi", "Cep Telefonu");
    define("_form_adres_eposta_yazi", "E-Posta");
    define("_form_adres_isim_yazi", "\u0130sim");
    define("_form_adres_soyisim_yazi", "Soyisim");
    define("_form_fatura_unvan_yazi", "Fatura \u00dcnvan \/ \u0130sim Soyisim");
    define("_form_fatura_vergi_dairesi_yazi", "Vergi Dairesi");
    define("_form_fatura_vergi_no_yazi", "Vergi No \/ Tc No");
    define("_form_buton_yazi", "G\u00f6nder");
    define("_anasayfa_tab_yeni_urun_yazi", "Yeni \u00fcr\u00fcnler");
    define("_anasayfa_baslik_firsat_urunleri_yazi", "F\u0131rsat \u00fcr\u00fcnleri");
    define("_anasayfa_sizin_icin_sectiklerimiz_yazi", "Sizin \u0130\u00e7in Se\u00e7tiklerimiz");
    define("_anasayfa_tab_indirimli_yazi", "\u0130ndirimli \u00dcr\u00fcnler");
    define("_anasayfa_hizli_kargo", "H\u0131zl\u0131 Kargo");
    define("_anasayfa_musteri_hizmetleri", "M\u00fc\u015fteri Hizmetleri");
    define("_anasayfa_guvenli_alis_veris", "G\u00fcvenli Al\u0131\u015f Veri\u015f");
    define("_anasayfa_kolay_iade", "Kolay \u0130ade");
    define("_body_cerez_ayar", "Ki\u015fiselle\u015ftir");
    define("_body_cerez_ayar_baslik", "\u00c7erez ve Tan\u0131mlama Teknolojileri Y\u00f6netim Paneli");
    define("_body_cerez_ayar_yazi", "\u0130nternet sitemizde \u00e7erez ve di\u011fer tan\u0131mlama teknolojileri vas\u0131tas\u0131yla ki\u015fisel verileriniz i\u015flenmektedir \u0130nternet sitemizde kullan\u0131lan \u00e7erezler ve di\u011fer tan\u0131mlama teknolojileri ile bunlar\u0131n kullan\u0131m ama\u00e7lar\u0131 hakk\u0131nda detayl\u0131 bilgiye \"\u00c7erez Politikas\u0131\" linkinden ula\u015fabilirsiniz Bu kapsamda zorunlu \u00e7erezler her zaman aktif olarak kullan\u0131lmakta olup, bunlar d\u0131\u015f\u0131nda kalan reklam-pazarlama \u00e7erezleriperformans analitik \u00e7erezler ve i\u015flevsel \u00e7erezler ise yaln\u0131zca a\u00e7\u0131k r\u0131zan\u0131z\u0131n bulunmas\u0131 halinde aktif hale getirilecektir \u00c7erez ve di\u011fer tan\u0131mlama teknolojilerinin tamam\u0131na onay vermeniz halinde T\u00fcm \u00c7erezleri Kabul Et ve tamam\u0131n\u0131 reddetmeniz halinde ise T\u00fcm \u00c7erezleri Reddet se\u00e7ene\u011fi ile ilerleyebilirsiniz Ayr\u0131ca, i\u015fbu \u00e7erez y\u00f6netim panelinden butonlar\u0131 tercihinize g\u00f6re a\u00e7\u0131k veya kapal\u0131 konuma getirerek onaylar\u0131n\u0131z\u0131 her zaman \u00f6zelle\u015ftirebilir ve tercihlerinizi kaydedebilirsiniz");
    define("_body_cerez_ayar_zorunlu_cerez_baslik", "Zorunlu \u00c7erezler");
    define("_body_cerez_ayar_zorunlu_cerez_yazi", "Zorunlu tan\u0131mlama bilgileri \u00e7evrim i\u00e7i mecralar\u0131m\u0131z\u0131n \u00e7al\u0131\u015fmas\u0131 ve talep etmi\u015f oldu\u011funuz bilgi toplumu hizmetlerinin (\u00f6rn log in olma, form doldurma, gizlilik tercihlerinin hat\u0131rlanmas\u0131, ziyaret\u00e7ilerin say\u0131lmas\u0131 ve trafi\u011fin \u00f6l\u00e7\u00fclmesi) yerine getirilebilmesi ama\u00e7lar\u0131yla kullan\u0131m\u0131 zorunlu olan tan\u0131mlama bilgileridir ve bu nedenle a\u00e7\u0131k r\u0131za hukuki \u015fart\u0131na dayanmamaktad\u0131r. Taray\u0131c\u0131 ayarlar\u0131n\u0131z\u0131 bu tan\u0131mlama bilgilerini engelleyecek veya sizi uyaracak \u015fekilde belirleyebilirsiniz. Ancak bu durumda internet sitemizin baz\u0131 b\u00f6l\u00fcmleri \u00e7al\u0131\u015fmayabilecektir. Yaln\u0131zca internet sitesinin veya uygulaman\u0131n hedef kitlesini \u00f6l\u00e7mek ve anonim istatistikler \u00fcretmek ile s\u0131n\u0131rl\u0131 ama\u00e7larla kullan\u0131lan birinci taraf performans analitik tan\u0131mlama bilgilerinin zorunlu tan\u0131mlama bilgileri kapsam\u0131nda de\u011ferlendirildi\u011fini hat\u0131rlatmak isteriz.");
    define("_body_cerez_ayar_zorunlu_reklam_pazarlama_baslik", "Reklam \/ Pazarlama \u00c7erezleri");
    define("_body_cerez_ayar_zorunlu_reklam_pazarlama_yazi", "Reklam \/ pazarlama tan\u0131mlama bilgileri kullan\u0131c\u0131lar\u0131n internet ortam\u0131ndaki faaliyetlerinin izlenmesi, bu faaliyetlerin analiz edilmesi ve kullan\u0131c\u0131lar\u0131n profillenmesi yoluyla kullan\u0131c\u0131lar\u0131n tercih ve be\u011fenilerine uygun daha ilgili \u00e7ekici ve ki\u015fiye \u00f6zel i\u00e7erikler sunulmas\u0131 ama\u00e7lar\u0131yla kullan\u0131lan tan\u0131mlama bilgileridir. S\u00f6z konusu tan\u0131mlama bilgileri \u015firketimiz veya \u00fc\u00e7\u00fcnc\u00fc taraf i\u015f ortaklar\u0131 taraf\u0131ndan a\u00e7\u0131k r\u0131zan\u0131za istinaden kullan\u0131labilir ve yaln\u0131zca ilginizi \u00e7ekebilecek reklam, kampanya, \u00fcr\u00fcn ve hizmetlerin taraf\u0131n\u0131za sunulmas\u0131n\u0131 sa\u011flar");
    define("_body_cerez_ayar_zorunlu_analitik_baslik", "Performans \/ Analitik \u00c7erezler");
    define("_body_cerez_ayar_zorunlu_analitik_yazi", "Yaln\u0131zca internet sitesinin veya uygulaman\u0131n hedef kitlesini \u00f6l\u00e7mek ve anonim istatistikler \u00fcretmek ile s\u0131n\u0131rl\u0131 ama\u00e7larla kullan\u0131lan birinci taraf performans analitik tan\u0131mlama bilgileri d\u0131\u015f\u0131ndaki performans ve analitik tan\u0131mlama bilgileri internet sitelerimizde ve uygulamalar\u0131m\u0131zda kullan\u0131c\u0131 davran\u0131\u015flar\u0131n\u0131n analiz edilmesi, internet sitemizin ve uygulamalar\u0131m\u0131z\u0131n iyile\u015ftirilmesi, tekil kullan\u0131c\u0131 say\u0131lar\u0131n\u0131n tahmin edilmesi, en etkili arama motoru anahtar kelimelerinin tespit edilmesi ve gezinme durumunuzun izlenmesi ama\u00e7lar\u0131yla kullan\u0131lan ve istatistiki \u00f6l\u00e7\u00fcme imkan veren tan\u0131mlama bilgileridir. S\u00f6z konusu tan\u0131mlama bilgileri \u015firketimiz veya \u00fc\u00e7\u00fcnc\u00fc taraf hizmet sa\u011flay\u0131c\u0131lar\u0131 taraf\u0131ndan a\u00e7\u0131k r\u0131zan\u0131za istinaden kullan\u0131labilir ve internet sitemizi, uygulamalar\u0131m\u0131z\u0131, hizmetlerimizi ve tekliflerimizi s\u00fcrekli olarak optimize ederek size m\u00fcmk\u00fcn olan en iyi internet sitesi deneyimini sunmam\u0131za olanak sa\u011flar");
    define("_body_cerez_ayar_zorunlu_cerez_kabul", "Her Zaman Etkin");
    define("_sepet_sayfasi_sepetim_yazi", "Al\u0131\u015f Veri\u015f Sepetim");
    define("_giris_form_eposta_yazi", "E-Posta");
    define("_giris_form_sifre_yazi", "\u015eifre");
    define("_giris_form_beni_hatirla_yazi", "Ben Hat\u0131rla");
    define("_giris_form_sifremi_unuttum_yazi", "\u015eifremi Unuttum");
    define("_giris_form_giris_yap_yazi", "Giri\u015f");
    define("_uye_ol_form_isim_yazi", "Ad");
    define("_uye_ol_form_soyisim_yazi", "Soyisim");
    define("_uye_ol_form_cep_telefonu_yazi", "Cep telefonu");
    define("_uye_ol_form_eposta_yazi", "E-posta");
    define("_uye_ol_form_sifre_yazi", "\u015eifre");
    define("_uye_ol_form_sozlesme_kabul_yazi", "S\u00f6zle\u015fme \u015fartlar\u0131n\u0131 kabul ediyorum.");
    define("_uye_ol_form_sozlesme_link_yazi", "S\u00f6zle\u015fmeyi buradan okuyabilirsiniz");
    define("_uye_ol_form_buton_yazi", "Kaydet");
    define("_uye_ol_form_eksiksiz_doldurun_yazi", "T\u00fcm alanlar\u0131 eksiksiz doldurun");
    define("_body_cerez_ayar_islevsel_cerez_baslik", "\u0130\u015flevsel \u00c7erezler");
    define("_body_cerez_ayar_islevsel_cerez_yazi", "\u0130\u015flevsel tan\u0131mlama bilgileri zorunlu tan\u0131mlama bilgileri d\u0131\u015f\u0131nda kalan ve bilgi toplumu hizmetlerini a\u00e7\u0131k\u00e7a talep etmi\u015f oldu\u011funuz haller hari\u00e7 olmak \u00fczere, internet sitelerimizin ve uygulamalar\u0131m\u0131z\u0131n daha i\u015flevsel k\u0131l\u0131nmas\u0131 ve tercihlerinizin hat\u0131rlanmas\u0131 yoluyla ki\u015fiselle\u015ftirilmesi (\u00f6rn tercih etti\u011finiz dil veya eri\u015fim sa\u011flad\u0131\u011f\u0131n\u0131z b\u00f6lgeye ba\u011fl\u0131 olarak internet sitemizin dilini ve g\u00f6r\u00fcm\u00fcn\u00fc de\u011fi\u015ftiren bilgileri hat\u0131rlamas\u0131) ama\u00e7lar\u0131yla kullan\u0131lan \u00e7erezlerdir. S\u00f6z konusu \u00e7erezler \u015firketimiz veya \u00fc\u00e7\u00fcnc\u00fc taraf hizmet sa\u011flay\u0131c\u0131lar\u0131 taraf\u0131ndan a\u00e7\u0131k r\u0131zan\u0131za istinaden kullan\u0131labilir.");
    define("_body_cerez_ayar_button_kaydet", "Tercihlerimi Kaydet");
    define("_body_cerez_ayar_button_kapat", "Kapat");
    define("_iletisim_baslik_yazi", "\u0130leti\u015fim");
    define("_iletisim_form_adsoyad_yazi", "Ad Soyad");
    define("_iletisim_form_eposta_yazi", "E-Posta");
    define("_iletisim_form_telefon_yazi", "Telefon");
    define("_iletisim_form_mesajiniz_yazi", "Mesaj\u0131n\u0131z");
    define("_iletisim_form_buton_yazi", "G\u00f6nder");
    define("_body_sayfa_bulunamadi", "Arad\u0131\u011f\u0131n\u0131z sayfa bulunamad\u0131 :(");
    define("_iletisim_bizi_takip_edin_yazi", "Bizi Takip Edin");
    define("_giris_form_sifre_hatirlat_baslik_yazi", "\u015eifre Hat\u0131rlat");
    define("_giris_form_sifre_hatirlat_buton_yazi", "G\u00f6nder");
    define("_uye_guncelle_form_basarili_yanit", "\u00dcye bilgileriniz g\u00fcncellenmi\u015ftir.");
    define("_uye_guncelle_form_basarisiz_yanit", "Bilgileriniz g\u00fcncelleneMedi. L\u00fctfen daha sonra tekrar deneyin.");
    define("_uye_ol_form_basarisiz_yanit", "Bir sorun olu\u015ftu, l\u00fctfen daha sonra tekrar deneyin");
    define("_uye_ol_form_basarili_yanit", "\u00dcye kayd\u0131n\u0131z tamamlanm\u0131\u015ft\u0131r. Size bir do\u011frulama e-postas\u0131 g\u00f6nderdik. L\u00fctfen e-posta adresinizi do\u011frulamay\u0131 unutmay\u0131n.");
    define("_uye_ol_form_sifre_dogrulama_yanit", "\u015eifreniz en az 8, en fazla 20 haneli olmal\u0131d\u0131r. 1 B\u00fcy\u00fck ve 1 k\u00fc\u00e7\u00fck harf i\u00e7ermelidir.");
    define("_uye_eposta_kayitli_degil", "Bu e-posta adresine kay\u0131tl\u0131 \u00fcye bulunmuyor");
    define("_uye_sifre_guncellenemedi", "\u015eifreniz G\u00fcncellenemedi");
    define("_uye_sifre_sifirlama", "\u015eifre S\u0131f\u0131rlama");
    define("_uye_sifre_sifirlama_eposta_sonuc", "\u015eifre s\u0131f\u0131rlama ba\u011flant\u0131s\u0131 e-posta adresinize g\u00f6nderildi.");
    define("_uye_sifre_sifirlama_eposta_sonuc_basarisiz", "\u015eifre s\u0131f\u0131rlama ba\u011flant\u0131s\u0131 e-posta adresinize g\u00f6nderilemedi.");
    define("_uye_kaydi_basarisiz", "\u00dcye kayd\u0131 yap\u0131lamad\u0131.");
    define("_uye_favori_ekle_basarisiz_yanit", "\u00dcr\u00fcn favorilere eklenemedi");
    define("_uye_favori_ekle_basarili_yanit", "\u00dcr\u00fcn favorilerinize eklendi.");
    define("_uye_favorilerim_baslik", "Favorilerim");
    define("_urun_detay_fav_cikar_yazi", "Favorilerden \u00c7\u0131kar");
    define("_uye_favori_cikar_basarili_yanit", "\u00dcr\u00fcn favorilerinizden \u00e7\u0131kar\u0131ld\u0131");
    define("_uye_favori_cikar_basarisiz_yanit", "\u00dcr\u00fcn favorilerinizden \u00e7\u0131kar\u0131l\u0131rken bir sorun olu\u015ftu");
    define("_uye_ol_eposta_konu", "\u00dcye kayd\u0131n\u0131z yap\u0131lm\u0131\u015ft\u0131r.");
    define("_uye_ol_eposta_title", "\u00dcye eposta do\u011frulama");
    define("_uye_ol_eposta_aciklama", "Merhaba, [name-surname] yeni \u00fcyelik i\u015fleminiz i\u00e7in te\u015fekk\u00fcr ederiz. \u00dcyeli\u011finizi tamamlamak i\u00e7in a\u015fa\u011f\u0131daki butona t\u0131klay\u0131n");
    define("_uye_ol_eposta_dogrula_buton", "E-posta Adresinizi Do\u011frulay\u0131n");
    define("_uye_ol_eposta_dogrula_buton_aciklama", "E\u011fer yukar\u0131daki butona t\u0131klayam\u0131yorsan\u0131z, a\u015fa\u011f\u0131daki ba\u011flant\u0131y\u0131 kopyalay\u0131p taray\u0131c\u0131n\u0131za yap\u0131\u015ft\u0131rabilirsiniz.");
    define("_uye_ol_eposta_bitis_yazi", "\u0130yi g\u00fcnler dileriz.");
    define("_uye_ol_eposta_gonderim_basarili", "\u00dcyeli\u011finiz tamamland\u0131 ve adresinize do\u011frulama e-postas\u0131 g\u00f6nderildi.");
    define("_uye_eposta_kayitli", "Bu e-posta adresi zaten kay\u0131tl\u0131");
    define("_uye_telefon_kayitli_degil", "Bu telefon kay\u0131tl\u0131 de\u011fil.");
    define("_uye_telefon_kayitli", "Bu telefon numaras\u0131 zaten kay\u0131tl\u0131.");
    define("_uye_ol_form_eposta_dogrulama_hata", "Eksik ya da yanl\u0131\u015f parametre. Do\u011frulama yap\u0131lamad\u0131.");
    define("_uye_ol_eposta_dogrulama_tamam", "E-posta adresiniz do\u011frulanm\u0131\u015ft\u0131r.");
    define("_uye_ol_form_spam_yazi", "\u00dcyelik form\u0131 bozuk. L\u00fctfen daha sonra tekrar deneyin.");
    define("_form_gonderim_basarili", "\u00dcyelik form\u0131 bozuk. L\u00fctfen daha sonra tekrar deneyin.");
    define("_uye_sifre_guncellendi", "\u015eifreniz do\u011frulanm\u0131\u015ft\u0131r.");
    define("_uye_adres_eklendi", "\u015eifreniz do\u011frulanm\u0131\u015ft\u0131r.");
    define("_uye_adres_eklenemedi", "\u015eifreniz do\u011frulanm\u0131\u015ft\u0131r.");
    define("_uye_adres_guncellendi", "\u015eifreniz do\u011frulanm\u0131\u015ft\u0131r.");
    define("_uye_adres_guncellenemedi", "\u015eifreniz do\u011frulanm\u0131\u015ft\u0131r.");
    define("_uye_adres_silindi", "\u015eifreniz do\u011frulanm\u0131\u015ft\u0131r.");
    define("_uye_adres_silinemedi", "\u00dcyelik form\u0131 bozuk. L\u00fctfen daha sonra tekrar deneyin.");
    define("_uye_ol_eposta_gonderim_basarisiz", "\u015eifreniz do\u011frulanm\u0131\u015ft\u0131r.");
    define("_uye_mesajlarim_baslik", "\u00dcye mesajlar\u0131m");
    define("_uye_mesaj_yaz_konu", "\u00dcye mesaj\u0131n\u0131z\u0131 yaz\u0131n");
    define("_uye_mesaj_yaz_baslik", "\u00dcye mesaj\u0131n\u0131z\u0131 yaz\u0131n");
    define("_uye_mesaj_yaz_icerik", "\u00dcye mesaj\u0131n\u0131z\u0131 yaz\u0131n");
    define("_uye_mesaj_yaz_buton", "\u00dcye mesaj\u0131n\u0131z\u0131 g\u00f6nder");
    define("_odeme_kredi_karti_odeme_yazi", "Kredi Kart\u0131 ile \u00f6deme");
    define("_odeme_havale_odeme_yazi", "Havale ile \u00f6deme");
    define("_odeme_kredi_karti_odeme_aciklama", "Kredi Kart\u0131 ile \u00f6deme");
    define("_odeme_havale_odeme_aciklama", "Havale ile \u00f6deme");
    define("_odeme_havale_siparis_kodu_yazi", "Havale bilgileriniz do\u011frulanm\u0131\u015ft\u0131r.");
    define("_odeme_siparisi_onayla_havale", "Havale bilgilerinizi do\u011frulay\u0131n");
    define("_odeme_siparisi_onayla_kapida_odeme", "Kap\u0131da \u00f6deme bilgilerinizi do\u011frulay\u0131n");
    define("_odeme_kapida_odeme_baslik", "Kap\u0131da \u00f6deme bilgilerinizi do\u011frulay\u0131n");
    define("_odeme_kapida_odeme_aciklama", "Kap\u0131da \u00f6deme bilgilerinizi do\u011frulay\u0131n");
    define("_odeme_banka_havalesi_odeme_baslik", "Havale ile \u00f6deme");
    define("_odeme_kredi_karti_odeme_baslik", "Kredi Kart\u0131 ile \u00f6deme");
    define("_odeme_siparis_basarili_yazi", "\u00dcyelik form\u0131 bozuk. L\u00fctfen daha sonra tekrar deneyin.");
    define("_odeme_siparis_no", "\u00dcyelik form\u0131 bozuk. L\u00fctfen daha sonra tekrar deneyin.");
    define("_odeme_siparislerim", "\u00dcyelik form\u0131 bozuk. L\u00fctfen daha sonra tekrar deneyin.");
    define("_odeme_siparis_eposta_basarili", "\u00dcyelik form\u0131 bozuk. L\u00fctfen daha sonra tekrar deneyin.");
    define("_odeme_basarisiz", "\u00dcyelik form\u0131 bozuk. L\u00fctfen daha sonra tekrar deneyin.");
    define("_odeme_basarili", "\u00dcyelik form\u0131 bozuk. L\u00fctfen daha sonra tekrar deneyin.");
    define("_uye_olun", "Üye Olun");
    define("_urun_detay_urun_ozellikleri","Ürün Özellikleri");
    define("_arama_sayfasi_arama_baslik", "Arama");
    define("_form_sifre_degistir","Şifre Değiştir");
    define("_uyelik_form_eski_sifre","Şifreniz");
    define("_uyelik_form_yeni_sifre","Yeni Şifreniz");
    define("_uyelik_form_yeni_sifre_tekrar","Yeni Şifre Tekrar");
    define("_iletisim_form_randevu_tarihi","Randevu Tarihi");
    define("_iletisim_form_randevu_saati","Randevu Saati");
    define("_iletisim_form_saat_seciniz","Saat Seçiniz");
    define("_iletisim_form_randevu_baslik","Online Randevu Formu");
}